#!/usr/bin/env bash

CONTEXT_MODULE_FILE_PATH="$MODULE_ROOT_DIRECTORY_PATH/$MODULE_NAMESPACE_VALUE.module.$CONTEXT_STATE.js";
MODULE_FILE_PATH="$MODULE_ROOT_DIRECTORY_PATH/$MODULE_NAMESPACE_VALUE.module.js"

[[ -f "$MODULE_FILE_PATH.backup" ]] && \
mv --force "$MODULE_FILE_PATH.backup" "$MODULE_FILE_PATH";

[[ -f "$CONTEXT_MODULE_FILE_PATH.backup" ]] &&	\
mv --force "$CONTEXT_MODULE_FILE_PATH.backup" "$CONTEXT_MODULE_FILE_PATH";

return 0;
