#!/usr/bin/env bash

CONTEXT_MODULE_FILE_PATH="$MODULE_ROOT_DIRECTORY_PATH/$MODULE_NAMESPACE_VALUE.module.$CONTEXT_STATE.js";
MODULE_FILE_PATH="$MODULE_ROOT_DIRECTORY_PATH/$MODULE_NAMESPACE_VALUE.module.js"

[[ -f "$CONTEXT_MODULE_FILE_PATH" ]] &&	\
[[ -f "$MODULE_FILE_PATH" ]] &&			\
cp "$MODULE_FILE_PATH" "$MODULE_FILE_PATH.backup";

[[ -f "$CONTEXT_MODULE_FILE_PATH" ]] &&									\
cp "$CONTEXT_MODULE_FILE_PATH" "$CONTEXT_MODULE_FILE_PATH.backup" &&	\
mv --force "$CONTEXT_MODULE_FILE_PATH" $MODULE_FILE_PATH;

return 0;
